# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTODO < Formula
  desc "A local-only list of TODO items for your git repositories."
  homepage "https://github.com/kapitanov/git-todo"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.1/git-todo_v0.0.1_macos_x86_64.tar.gz"
      sha256 "d98bad800e21c1087c6abbb855441b901b6ed39328dcc86a7525d9e65d8d74d9"

      def install
          bin.install "git-todo"
      end
    end
    on_arm do
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.1/git-todo_v0.0.1_macos_arm64.tar.gz"
      sha256 "9dfc6e761adaf58d876297209f556ab83d12ff576b632004b0204cf747234df1"

      def install
          bin.install "git-todo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kapitanov/git-todo/releases/download/v0.0.1/git-todo_v0.0.1_linux_x86_64.tar.gz"
        sha256 "9cdf8e5da2a83f08a10e530d4099b93d4dd23a8d404749256d21d54f3eeb611f"

        def install
          bin.install "git-todo"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kapitanov/git-todo/releases/download/v0.0.1/git-todo_v0.0.1_linux_arm.tar.gz"
        sha256 "51db6ccdd31feb6efdeaeaad5ff40b486c6a96f2b8505fc004d967cd6b3c974a"

        def install
          bin.install "git-todo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kapitanov/git-todo/releases/download/v0.0.1/git-todo_v0.0.1_linux_arm64.tar.gz"
        sha256 "c8d082e7365a3c9667deafc602e9bdc28b7e18aa8add3651c3c0f4325ebe661b"

        def install
          bin.install "git-todo"
        end
      end
    end
  end
end