# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTodo < Formula
  desc "A local-only list of TODO items for your git repositories"
  homepage "https://github.com/kapitanov/git-todo"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.2/git-todo_v0.0.2_macos_x86_64.tar.gz"
      sha256 "309c1426c13b4aaa24ee38aecce083adb00dad5c876cdc4b92967b2e1d7ce881"

      def install
        bin.install "git-todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.2/git-todo_v0.0.2_macos_arm64.tar.gz"
      sha256 "ad8d2fd692c5bb050e730c9dc88fde00e19309bb0b6fd4bcca0ce3af84c445f6"

      def install
        bin.install "git-todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.2/git-todo_v0.0.2_linux_x86_64.tar.gz"
      sha256 "ba26b90858829b6d49c63da920185883725b8142ce47b75161a5c1d20de33131"
      def install
        bin.install "git-todo"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.2/git-todo_v0.0.2_linux_arm.tar.gz"
      sha256 "852a23d2bcd2a1491463f4efed058925f0041bf9bdff67c6dee14407f386bfb1"
      def install
        bin.install "git-todo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kapitanov/git-todo/releases/download/v0.0.2/git-todo_v0.0.2_linux_arm64.tar.gz"
      sha256 "5997ee7cd5c197463067694c517c60c5878ec7fd8cc1054e972ee59a0c0413a9"
      def install
        bin.install "git-todo"
      end
    end
  end
end
