# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xgoimports < Formula
  desc "A better goimports that keeps your imports sorted and grouped nicely"
  homepage "https://github.com/kapitanov/xgoimports"
  version "0.1.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapitanov/xgoimports/releases/download/v0.1.0/xgoimports_v0.1.0_macos_x86_64.tar.gz"
      sha256 "f0504f71c0ad72cc5170b3f6a0b33d564191791773e0148e12aed773f560415e"

      def install
        bin.install "xgoimports"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapitanov/xgoimports/releases/download/v0.1.0/xgoimports_v0.1.0_macos_arm64.tar.gz"
      sha256 "0f7cba6f68755577524a55f963b1fcda4150e6263749602ebffed4ff9a975b82"

      def install
        bin.install "xgoimports"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kapitanov/xgoimports/releases/download/v0.1.0/xgoimports_v0.1.0_linux_x86_64.tar.gz"
      sha256 "81b20945b16527729596bef4dfa7076d822054422d4d0c032e031af2560139ce"
      def install
        bin.install "xgoimports"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/kapitanov/xgoimports/releases/download/v0.1.0/xgoimports_v0.1.0_linux_arm.tar.gz"
      sha256 "8e36758d886389374b5cab8faf5b233361b3de824f54d8c19e7754dc41ec3aaf"
      def install
        bin.install "xgoimports"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kapitanov/xgoimports/releases/download/v0.1.0/xgoimports_v0.1.0_linux_arm64.tar.gz"
      sha256 "4feabfc1a62a04741790a51fed71668507e6a828a9ae6aeb9c7985d7ad98eadc"
      def install
        bin.install "xgoimports"
      end
    end
  end
end
